deployment:
  tasks:
    - export REPOPATH=/vitalyreutsky/portfolio/app*
    - export SITEPATH=/vitalyreutsky/portfolio/app/
    - /bin/rsync -rav --exclude '.git' --exclude '.cpanel.yml' --del $REPOPATH $SITEPATH
